Update check.yml

diff --git a/.github/workflows/check.yml b/.github/workflows/check.yml
--- a/.github/workflows/check.yml
+++ b/.github/workflows/check.yml
@@ -14,22 +14,34 @@ jobs:
         id: check_1_files
         uses: andstor/file-existence-action@v1
         with:
-          files: "osm_qgis_screenshot.png"
+          files: "screencap-island-area.png"
 
       - name: Required files exist
         if: steps.check_1_files.outputs.files_exists != 'true'
         run: |
-          echo Required file, 'osm_qgis_screenshot.png', is missing
+          echo Required file, 'screencap-island-area.png', is missing
+          exit 1
+          
+      - name: Check Screenshot
+        id: check_2_files
+        uses: andstor/file-existence-action@v1
+        with:
+          files: "screencap_road_length.png"
+
+      - name: Required files exist
+        if: steps.check_2_files.outputs.files_exists != 'true'
+        run: |
+          echo Required file, 'screencap_road_length.png', is missing
           exit 1
           
       - name: Check Script
         id: check_script
         uses: andstor/file-existence-action@v1
         with:
-          files: "import.cmd"
+          files: "import.sh"
 
       - name: Required script exist
         if: steps.check_script.outputs.files_exists != 'true'
         run: |
-          echo Required file, 'import.cmd', is missing
+          echo Required file, 'import.sh', is missing
           exit 1
